# Site Settings
title: Listen
email: contactdominicward+github@gmail.com
description: >
    Blank
baseurl: ""
url: https://deeuu.github.io/listen/
permalink: /:title/
github_username: deeuu
# Build Settings
sass:
  sass_dir: assets/_sass
include: ['_pages']
kramdown:
  input: GFM
