# Site Settings
title: "Listen"
email: "contactdominicward+github@gmail.com"
description: >
    "Blank"
baseurl: ""
url: "https://deeuu.github.io/listen"
permalink: /:title/
github:
    - username: "deeuu"
    - repository : "listen"
    - branch: "listen"

staticman:
    branch: "gh-pages"
# Build Settings
sass:
  sass_dir: assets/_sass
include: ['_pages']
kramdown:
  input: GFM
