# Site Settings
title: "SiSEC MUS18 Subjective Evaluation - Listening Test"
description: >
    "Run listening tests in the browser locally or via GitHub pages"
baseurl: ""
url: "https://ryanckim.github.io/listen-sisec-mus-18-subjective-evaluation"

github:
    username: "ryanckim"
    repository : "listen-sisec-mus-18-subjective-evaluation"
    branch: "gh-pages"

# Build Setting
include: 
    - '_pages'
exclude:
  - package.json
  - node_modules
  - gulpfile.js

kramdown:
  input: GFM
